main: *.o
	g++ -o main *.o

*.o: *.h *.cpp
	g++ -g -c *.cpp

run:
	./main

clean:
	rm *.o main

# OBJS	= main.o Core.o Falcon.o Falcon9.o MerlinRocket.o MerlinVac.o Stage.o StageOne.o StageTwo.o FalconHeavy.o CoreAdapter.o Dragon.o DragonCrew.o Spacecraft.o StageAttached.o StageDettached.o Boost.o Button.o Cargo.o Command.o Left.o Right.o Satellite.o Simulation.o Slow.o CoreMemento.o CoreAdapterMemento.o CoreState.o
# SOURCE	= main.cpp Core.cpp Falcon.cpp Falcon9.cpp MerlinRocket.cpp MerlinVac.cpp Stage.cpp StageOne.cpp StageTwo.cpp FalconHeavy.cpp CoreAdapter.cpp Dragon.cpp DragonCrew.cpp Spacecraft.cpp StageAttached.cpp StageDettached.cpp Boost.cpp Button.cpp Cargo.cpp Command.cpp Left.cpp Right.cpp Satellite.cpp Simulation.cpp Slow.cpp CoreMemento.cpp CoreAdapterMemento.cpp
# HEADER	= Core.h Falcon.h Falcon9.h MerlinRocket.h MerlinVac.h Stage.h StageOne.h StageTwo.h FalconHeavy.h CoreAdapter.h Dragon.h DragonCrew.h Spacecraft.h StageAttached.h StageDettached.h Boost.h Button.h Cargo.h Command.h Left.h Right.h Satellite.h Simulation.h Slow.h CoreMemento.h CoreAdapterMemento.h
# OUT	= a.out
# CC	 = g++
# FLAGS	 = -g -c 
# LFLAGS	 =

# all: $(OBJS)
# 	$(CC) -g $(OBJS) -o $(OUT) $(LFLAGS)


# main.o: main.cpp
# 	$(CC) $(FLAGS) main.cpp

# Core.o: Core.cpp
# 	$(CC) $(FLAGS) Core.cpp

# Falcon.o: Falcon.cpp
# 	$(CC) $(FLAGS) Falcon.cpp

# Falcon9.o: Falcon9.cpp
# 	$(CC) $(FLAGS) Falcon9.cpp

# MerlinRocket.o: MerlinRocket.cpp
# 	$(CC) $(FLAGS) MerlinRocket.cpp

# MerlinVac.o: MerlinVac.cpp
# 	$(CC) $(FLAGS) MerlinVac.cpp

# Stage.o: Stage.cpp
# 	$(CC) $(FLAGS) Stage.cpp

# StageOne.o: StageOne.cpp
# 	$(CC) $(FLAGS) StageOne.cpp

# StageTwo.o: StageTwo.cpp
# 	$(CC) $(FLAGS) StageTwo.cpp

# FalconHeavy.o: FalconHeavy.cpp
# 	$(CC) $(FLAGS) FalconHeavy.cpp

# CoreAdapter.o: CoreAdapter.cpp
# 	$(CC) $(FLAGS) CoreAdapter.cpp

# Dragon.o: Dragon.cpp
# 	$(CC) $(FLAGS) Dragon.cpp

# DragonCrew.o: DragonCrew.cpp
# 	$(CC) $(FLAGS) DragonCrew.cpp

# Spacecraft.o: Spacecraft.cpp
# 	$(CC) $(FLAGS) Spacecraft.cpp

# Boost.o: Boost.cpp
# 	$(CC) $(FLAGS) Boost.cpp

# Button.o: Button.cpp
# 	$(CC) $(FLAGS) Button.cpp

# Cargo.o: Cargo.cpp
# 	$(CC) $(FLAGS) Cargo.cpp

# Command.o: Command.cpp
# 	$(CC) $(FLAGS) Command.cpp

# ConcretePerson.o: ConcretePerson.cpp
# 	$(CC) $(FLAGS) ConcretePerson.cpp

# Left.o: Left.cpp
# 	$(CC) $(FLAGS) Left.cpp

# Person.o: Person.cpp
# 	$(CC) $(FLAGS) Person.cpp

# Right.o: Right.cpp
# 	$(CC) $(FLAGS) Right.cpp

# Satellite.o: Satellite.cpp
# 	$(CC) $(FLAGS) Satellite.cpp

# Simulation.o: Simulation.cpp
# 	$(CC) $(FLAGS) Simulation.cpp

# Slow.o: Slow.cpp
# 	$(CC) $(FLAGS) Slow.cpp

# CoreMemento.o: CoreMemento.cpp
# 	$(CC) $(FLAGS) CoreMemento.cpp

# CoreAdapterMemento.o: CoreAdapterMemento.cpp
# 	$(CC) $(FLAGS) CoreAdapterMemento.cpp

# clean:
# 	rm -f $(OBJS) $(OUT)

# run: $(OUT)
# 	./$(OUT)